[project]
name = "bpo"
version = "0.4.0"
description = "CLI to optimize prompts with AWS Bedrock"
authors = [
    {name = "Michael Rowlinson"},
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.41.2",
    "pyperclip>=1.11.0",
    "questionary>=2.1.1",
    "typer>=0.20.0",
]

[project.urls]
Homepage = "https://github.com/rowlinsonmike/bedrock-prompt-optimizer"

[project.scripts]
bpo = "bpo.main:app"

[tool.setuptools.packages.find]
where = ["src"]
